### ISSUE TITLE
Messing up with fonts declaration

### ISSUE THREAD

**Issue by ishaquehassan** [Fly-Mix/flr-as-plugin#1]
@YK-Unit This is a great plugin really appreciate your team efforts. But actually its messing up with my fonts declaration. So am unable to use it. Can you please address that! 

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/5463915/77102920-6f3b6680-6a3b-11ea-99b7-6e9273584165.png">

<img width="691" alt="image" src="https://user-images.githubusercontent.com/5463915/77104564-073a4f80-6a3e-11ea-9022-46114034cab2.png">

Am using latest stable android studio & latest flutter SDK version

<img width="846" alt="image" src="https://user-images.githubusercontent.com/5463915/77103182-d5c08480-6a3b-11ea-8154-36dafdec9214.png">
<img width="986" alt="image" src="https://user-images.githubusercontent.com/5463915/77103676-9b0b1c00-6a3c-11ea-8aaa-686467b35c0b.png">

**Comment by YK-Unit** [comment]
1. We will fix this bug as soon as possible. Until then, you can use [flr-cli](https://github.com/Fly-Mix/flr-cli) instead of the plugin.  
2. We will also address the feature supports fonts asset, but this will take some time.
3. Thanks for your issue.

**Comment by YK-Unit** [comment]
@ishaquehassan [flr-as-plugin v0.2.1 ](https://plugins.jetbrains.com/plugin/13789-flr/update/81372) (for Android Studio 3.6) and [flr-as-plugin v0.1.2](https://plugins.jetbrains.com/plugin/13789-flr/update/81368) (for Android Studio 3.5) do fix this issue,  you can install it form plugin market now. Enjoy ~ ^_^ ~

**Comment by YK-Unit** [comment]
hey, @ishaquehassan, here a good news, now [the latest flr-as-plugin(v192.1.0.0 for Android Studio 3.6)](https://plugins.jetbrains.com/plugin/13789-flr/update/82052) did support for processing font assets (` .ttf`, `.otf`, `.ttc`).  You can install it from plugin marketplace now . Enjoy~
