### ISSUE TITLE
incompatible with AndroidStudio 4.0

### ISSUE THREAD

**Issue by d-silveira** [Fly-Mix/flr-as-plugin#10]
upon updating Android Studio to 4.0, 
it says flr is incompatible,

can you  please check this out.

Thanks,
Regards

**Comment by YK-Unit** [comment]
Ok, we will check it and add the support for Android Studio 4.0

**Comment by YK-Unit** [comment]
You can temporarily use the [flr-cli version](https://github.com/Fly-Mix/flr-cli) instead of the plugin.

To install or update flr-cli, just run:
``` shell
sudo gem install flr
```

**Comment by YK-Unit** [comment]
[flr-as-plugin-193.3.1.0](https://plugins.jetbrains.com/plugin/13789-flr/update/87609) which is compatible with Android Studio 4.0 is released now, you can install it from the marketplace of  Android Studio. Enjoy ~
