### ISSUE TITLE
可否将获取资源的方法改为get方式获取

### ISSUE THREAD

**Issue by nullptrx** [Fly-Mix/flr-as-plugin#11]
```dart
  AssetImage icon() {
    return AssetImage(asset.icon.keyName);
  }

  /// replace with
  AssetImage get icon => AssetImage(asset.icon.keyName);

```

**Comment by YK-Unit** [comment]
- 在工具初期，获取资源的方式是设计为`get方式`获取的
- 随着增加SVG资源、文本资源的支持，为了使获取普通图片资源、SVG资源、文本资源的方式保持一致性，重新把获取方式设计为了`function方式`
- 另外，相比`get方式`，`function方式`具备更好的兼容性和可扩展性，使得工具在新增特性支持（比如增加黑暗模式资源支持）时，不会容易导致发生breaking式的升级
- 综上，所以目前不会选择把获取资源方式改为`get方式`
