### ISSUE TITLE
Android Studio 4.1插件市场搜索不到

### ISSUE THREAD

**Issue by lvyandev** [Fly-Mix/flr-as-plugin#12]
RT

**Comment by YK-Unit** [comment]
感谢反馈。目前尚未推出支持Android Studio 4.1的版本，所以在Android Studio 4.1插件市场搜索不到该插件。
支持Android Studio 4.1的版本稍后会推出，敬请期待。

**Comment by YK-Unit** [comment]
@lvyandev 
[flr-as-plugin v201.3.2.0](https://plugins.jetbrains.com/plugin/13789-flr/versions/stable/99704) is released for Android Studio 4.1 now, you can install it from Android Studio marketplace or download it form [jetbrains marketplace](https://plugins.jetbrains.com/plugin/13789-flr/versions/stable/99704) now.
