### ISSUE TITLE
Please add support for null-safety

### ISSUE THREAD

**Issue by kevinls-coder** [Fly-Mix/flr-as-plugin#13]
Hi:

This plugin is wonderful, but when I updated my project to flutter 2.0, like this below:  
```
environment:
  sdk: '>=2.12.0 <3.0.0'
```
r.g.dart  reported some errors for null-safety . So, could you please add support for null-safety?

thanks a lot.

**Comment by YK-Unit** [comment]
We are planing to support it.

**Comment by YK-Unit** [comment]
> Hi:
> 
> This plugin is wonderful, but when I updated my project to flutter 2.0, like this below:
> 
> ```
> environment:
>   sdk: '>=2.12.0 <3.0.0'
> ```
> 
> r.g.dart reported some errors for null-safety . So, could you please add support for null-safety?
> 
> thanks a lot.

- [flr-cli-v3.2.0](https://rubygems.org/gems/flr/versions/3.2.0) which supports for nullsafety is released , and you can install it now.  See more details from https://github.com/Fly-Mix/flr-cli .  
- flr-as-plugin is still developing for nullsafety--and in fact it needs some time.

**Comment by YK-Unit** [comment]
Flutter资源管理工具 Flr Android Studio Plugin 版本 flr-as-plugin-x.3.3.0 已经正式发布:

1. 适配 Dart 2.12，支持 nullsafety

2. Demos：

- flutter_r_demo：https://github.com/Fly-Mix/flutter_r_demo/tree/test/flr-core-3.2.0-nullsafety
- flutter_hello_package：https://github.com/Fly-Mix/flutter_hello_package/tree/test/flr-core-3.2.0-nullsafety

3. Plugin HomePage：https://plugins.jetbrains.com/plugin/13789-flr
