### ISSUE TITLE
Flr plugin 无法下载

### ISSUE THREAD

**Issue by tall-nuts** [Fly-Mix/flr-as-plugin#14]
Flr plugin 在 Android Studio Plugin Market检索不到。从官网可以找到插件，但是下载下来从本地导入报错。

![image](https://user-images.githubusercontent.com/9261499/118428768-c225b200-b702-11eb-9194-3481c949bd9b.png)
![image](https://user-images.githubusercontent.com/9261499/118428859-eed9c980-b702-11eb-9153-50acd3e06c20.png)

**Comment by YK-Unit** [comment]
Android Studio 升级了IDEA内核，flr-as-plugin 需要做适配才行。这个请稍等些许日子。

**Comment by YK-Unit** [comment]
flr-as-plugin 目前已支持 Android Studio 4.2，你可前往下载Android Studio Plugin Market 或者[官网](https://plugins.jetbrains.com/plugin/13789-flr/versions/stable/120330) 下载v202.3.3.0 版本。
