### ISSUE TITLE
请支持AndroidStudio最新稳定版

### ISSUE THREAD

**Issue by for7GG** [Fly-Mix/flr-as-plugin#17]

**Comment by YK-Unit** [comment]
Flutter资源管理工具 Flr Android Studio Plugin 版本 flr-as-plugin-203.3.3.1 正式发布:

1. 支持 Android Studio Arctic Fox | 2020.3.1

你可以直接在 Android Studio marketplace 安装，也可以前往 jetbrains marketplace（https://plugins.jetbrains.com/plugin/13789-flr/versions/stable/133756）下载安装。
