### ISSUE TITLE
开启监测，粘贴的文件变动无法检测到吗？

### ISSUE THREAD

**Issue by magical-xu** [Fly-Mix/flr-as-plugin#18]
问题描述：
我开启了自动检测这个功能，但是copy图片 粘贴到 assets 里没有自动修改 yaml 文件。但是在该目录里 新建文件是可以的，请问是不支持吗？

环境：
macOS版本：
![image](https://user-images.githubusercontent.com/15309220/131069086-c14b6576-d8ef-4465-ad94-bd2b55edcc0e.png)

Android studio 版本：4.1.3
Flutter版本：2.2.2
Dart版本：2.13.3

Flr 插件版本：201.3.3.1

控制台输出：
![image](https://user-images.githubusercontent.com/15309220/131069415-661cd754-615e-42b2-9bd9-310893b4a53c.png)

**Comment by YK-Unit** [comment]
Flr插件是支持监控粘贴文件这种操作的，但是它依赖于Android Studio IDE的文件系统：即你在磁盘上完成了文件粘贴操作后，Android Studio IDE的文件系统需要先识别出来，通知给Flr插件后，Flr插件才能完成后续操作。

另外，Android Studio IDE的文件系统对磁盘操作的识别不是实时的，有一定的滞后性。

PS：目前Android Studio IDE已经推出最新版本：Android Studio Arctic Fox | 2020.3.1 ，建议使用新版本Android Studio IDE。始终新版相比旧版，bug会少一点。
