### ISSUE TITLE
请支持最新稳定版

### ISSUE THREAD

**Issue by for7GG** [Fly-Mix/flr-as-plugin#21]

**Comment by YK-Unit** [comment]
正在排期中

**Comment by YK-Unit** [comment]
> _No description provided._

你当前用的最新稳定版本是： Android Studio Bumblebee | 2021.1.1 Patch 1 ？

**Comment by YK-Unit** [comment]
[flr-as-plugin v211.3.3.1](https://plugins.jetbrains.com/plugin/13789-flr/versions/stable/159229) is released for **Android Studio Bumblebee** now.
