### ISSUE TITLE
请支持最新稳定版AndroidStudio Dolphin

### ISSUE THREAD

**Issue by for7GG** [Fly-Mix/flr-as-plugin#24]
如题

**Comment by YK-Unit** [comment]
近期会抽空进行适配

**Comment by YK-Unit** [comment]
Flutter资源管理工具 Flr Android Studio Plugin 版本 flr-as-plugin-213.3.3.1 正式发布:

1. 支持 Android Studio Dolphin | 2021.3.1

你可以直接在 Android Studio marketplace 安装，也可以前往 jetbrains marketplace（https://plugins.jetbrains.com/plugin/13789-flr/versions/stable/228523 ）下载安装。
更多详情可看：https://github.com/Fly-Mix/flr-as-plugin
