### ISSUE TITLE
need update 

### ISSUE THREAD

**Issue by writewhite** [Fly-Mix/flr-as-plugin#25]

**Comment by ripeyd** [comment]
Plugin 'Flr' (version '213.3.3.1') is not compatible with the current version of the IDE, because it requires build 213. * or older but the current build is AI-221.6008.13

**Comment by YK-Unit** [comment]
> Plugin 'Flr' (version '213.3.3.1') is not compatible with the current version of the IDE, because it requires build 213. * or older but the current build is AI-221.6008.13

👌~

**Comment by YK-Unit** [comment]
Flutter资源管理工具 Flr Android Studio Plugin 版本 flr-as-plugin-221.3.3.1 正式发布:

1. 支持 Android Studio Electric Eel | 2022.1.1

你可以直接在 Android Studio marketplace 安装，也可以前往 [jetbrains marketplace](https://plugins.jetbrains.com/plugin/13789-flr/versions/stable/282018)下载安装。
