### ISSUE TITLE
麻烦适配一下最新as

### ISSUE THREAD

**Issue by jxtx123456** [Fly-Mix/flr-as-plugin#26]
最新版本：Giraffe | 2022.3.1

**Comment by YK-Unit** [comment]
好的~~

**Comment by YK-Unit** [comment]
Flutter资源管理工具 Flr Android Studio Plugin 新版发布：
1. flr-as-plugin-222.3.3.1 版本：支持 Android Studio Flamingo | 2022.2.1
2. flr-as-plugin-223.3.3.1 版本：支持 Android Studio Giraffe | 2022.3.1

你可以直接在 Android Studio marketplace 安装，也可以前往 jetbrains marketplace（https://plugins.jetbrains.com/plugin/13789-flr/versions ）下载安装。
