### ISSUE TITLE
请支持一下最新版的Android Studio Hedgehog | 2023.1.1

### ISSUE THREAD

**Issue by aleiin** [Fly-Mix/flr-as-plugin#27]
![image](https://github.com/Fly-Mix/flr-as-plugin/assets/38730268/8bc02509-4f25-4016-9720-0bfc089ef600)

**Comment by YK-Unit** [comment]
[flr-as-plugin-231.3.3.1 版本]( https://plugins.jetbrains.com/plugin/13789-flr/versions/stable/455134)：支持Android Studio Hedgehog | 2023.1.1
