### ISSUE TITLE
assets folder below lib doesn't work

### ISSUE THREAD

**Issue by d-silveira** [Fly-Mix/flr-as-plugin#4]
hi,

I always keep my assets folder next to lib, but using flr I can't since it refuses to generate.

Thanks alot,
regards

**Comment by YK-Unit** [comment]
> hi,
> 
> I always keep my assets folder next to lib, but using flr I can't since it refuses to generate.
> 
> Thanks alot,
> regards

Can you run `tree  -L 5` or take a picture to show me your flutter project's resource structure as the below:

```
  flutter_project_root_dir
  ├── build
  │   ├── ..
  ├── lib
  │   ├── assets
  │   │   ├── images
```
