### ISSUE TITLE
媒体文件如何添加到assets中

### ISSUE THREAD

**Issue by nothinggift** [Fly-Mix/flr-as-plugin#6]
Flr很好用，节省了很多枯燥的操作，最重要的是用一些资源时，终于有提示了

我想知道对于Flr现在不支持的文件类型，比如音乐或者视频文件，我该如何添加到assets中

我并不需要Flr支持这些类型，因为数量很小，但我一旦手动添加到assets中，他就会被自动生成的代码覆盖，我看了文档和示例，都没有解决方案。建议在flr的配置里加上一个自定义assets，生成代码时，只需要将自定义里的路径原封不动的搬过去就可以。

**Comment by YK-Unit** [comment]
> 建议在flr的配置里加上一个自定义assets，生成代码时，只需要将自定义里的路径原封不动的搬过去就可以。

这是一个非常好的建议！我们会对这种需求场景去做进一步的优化！敬请关注和期待~

**Comment by YK-Unit** [comment]
flr-as-plugin v3.1.0 系列（[v191.3.1.0, v192.3.1.0](https://plugins.jetbrains.com/plugin/13789-flr/versions)）已正式发布，欢迎下载使用：

1. 支持处理多工程（在同一工作空间的flutter主工程和其所有子工程）

2. 支持自动合并旧的资产声明——这意味着，开发者手动添加的资产声明会自动保留，不会再被Flr冲掉

   注意：自动合并时一个旧的资产声明时，Flr会检测该资产声明是否存在对应的资源文件，若不存在，就不保留该资产声明。
