### ISSUE TITLE
html,js等文件是否可以支持一下.我想实现一个内部jsbridge

### ISSUE THREAD

**Issue by liuyang-kevin** [Fly-Mix/flr-as-plugin#7]

**Comment by YK-Unit** [comment]
这个是可以的。然后，请问一下，你们在使用html,js等文件时，也是通过`loadString`方式（如`rootBundle.loadString(asset.test__yaml.keyName)`）读取吗？

**Comment by liuyang-kevin** [comment]
我到没想那么复杂。就是想随assets打包，远端的H5，script写一个本地路径懒加载一下，在判下undefined就完事儿了。

如果手动加assets配置，用flr生成配置貌似会被刷掉。

一会我试试你说的方法，这种注入方式貌似更好。

**Comment by YK-Unit** [comment]
那我了解你的需求了。目前flr的确会冲掉所有的assets配置。后面会对这种场景进行优化，避免冲掉用户额外的配置。

**Comment by YK-Unit** [comment]
flr-as-plugin v3.1.0 系列（[v191.3.1.0, v192.3.1.0](https://plugins.jetbrains.com/plugin/13789-flr/versions)）已正式发布，欢迎下载使用：

1. 支持处理多工程（在同一工作空间的flutter主工程和其所有子工程）

2. 支持自动合并旧的资产声明——这意味着，开发者手动添加的资产声明会自动保留，不会再被Flr冲掉

   注意：自动合并时一个旧的资产声明时，Flr会检测该资产声明是否存在对应的资源文件，若不存在，就不保留该资产声明。
