### ISSUE TITLE
不支持多模块

### ISSUE THREAD

**Issue by tangxiangpi** [Fly-Mix/flr-as-plugin#9]
比如flutter模块A依赖flutter模块B，B模块assets目录下有资源文件，在B模块的pubspec.yaml中增加对r_dart_library的依赖，如果studio打开A模块，我发现B模块无法生成r.dart文件，如果studio打开B模块，可以生成r.dart文件，但是pubspec.yaml没有添加对assets下面资源文件的引用

**Comment by YK-Unit** [comment]
目前暂时不支持多工程的递归解析。后面会增加此特性。

**Comment by tangxiangpi** [comment]
ok good job!

**Comment by tangxiangpi** [comment]
这里有一个bug，假如我的模块B叫做settingfluttermodule，生成的r.dart文件中
![image](https://user-images.githubusercontent.com/18000558/82418468-9cde7380-9aaf-11ea-98af-762b74c62d0a.png)，packageName是null，而实际中因为这是一个子模块，打包apk后，这个模块的资源实际在
![image](https://user-images.githubusercontent.com/18000558/82418570-b8e21500-9aaf-11ea-8f4a-e8a86aaa4907.png)
packages目录下面，所以上面的packageName应该为实际的模块名，否则引用到的资源文件是assets目录下，而不是子模块对应的packages目录下

**Comment by YK-Unit** [comment]
你提的这个问题，我如果没理解错的话，这个在3.0.0版本已经解决的了。
PS：如果需要示例，你也可以看看这个针对3.0.0版本的示例Demo：[flutter_hello_package](https://github.com/Fly-Mix/flutter_hello_package)

**Comment by YK-Unit** [comment]
flr-as-plugin v3.1.0 系列（[v191.3.1.0, v192.3.1.0](https://plugins.jetbrains.com/plugin/13789-flr/versions)）已正式发布，欢迎下载使用：

1. 支持处理多工程（在同一工作空间的flutter主工程和其所有子工程）

2. 支持自动合并旧的资产声明——这意味着，开发者手动添加的资产声明会自动保留，不会再被Flr冲掉

   注意：自动合并时一个旧的资产声明时，Flr会检测该资产声明是否存在对应的资源文件，若不存在，就不保留该资产声明。
